<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CashBookEntry;
use App\Models\Branch;
use App\Models\AccountHead;
use Illuminate\Support\Str;

class CashBookDummySeeder extends Seeder
{
    public function run(): void
    {
        $branches = Branch::all();
        $accountHeads = AccountHead::all();

        if ($branches->isEmpty() || $accountHeads->isEmpty()) {
            echo "Cannot run CashBookDummySeeder: Branches or AccountHeads are empty.\n";
            return;
        }

        $modes = ['Cash', 'Bank Transfer', 'UPI', 'Cheque'];
        $types = ['CREDIT', 'DEBIT'];

        for ($i = 1; $i <= 50; $i++) {
            $branch = $branches->random();
            $accountHead = $accountHeads->random();
            $type = $types[array_rand($types)];
            $mode = $modes[array_rand($modes)];

            CashBookEntry::create([
                'voucher_no' => 'VOUCHER-' . strtoupper(Str::random(4)) . '-' . $i,
                'transaction_date' => now()->subDays(rand(0, 30))->format('Y-m-d'),
                'transaction_type' => $type,
                'account_head_id' => $accountHead->id,
                'amount' => rand(500, 5000),
                'branch_id' => $branch->id,
                'paid_to_receive_from' => 'Dummy Person ' . $i,
                'mode_of_pay' => $mode,
                'dd_cheque_no' => $mode == 'Cheque' ? 'CHQ' . rand(10000, 99999) : null,
                'dd_cheque_date' => $mode == 'Cheque' ? now()->format('Y-m-d') : null,
                'drawn_on_bank' => $mode == 'Cheque' ? 'HDFC Bank' : null,
                'authorised_by' => 'Admin',
                'paid_by_received_by' => 'Staff Member',
                'remarks' => 'Dummy ' . $type . ' entry generated by seeder',
                'is_closing_entry' => false,
            ]);
        }
    }
}
